version: '3'
services:
  proyecto:
    image: postgres:13
    env_file:
      - ./data/.env
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
      - ./data/00-database.sql:/docker-entrypoint-initdb.d/00-database.sql
      - ./data/01-triggers.sql:/docker-entrypoint-initdb.d/01-triggers.sql
      - ./data/02-records.sql:/docker-entrypoint-initdb.d/02-functions.sql
